import type { AssessmentSection, PlacementLocale, PlacementLevel } from "./types";

const sharedCourses: Record<PlacementLevel, { ar: string; en: string }> = {
  A1: { ar: "ابدأ من A1", en: "Start with A1" },
  A2: { ar: "ابدأ من A2", en: "Start with A2" },
  B1: { ar: "ابدأ من B1", en: "Start with B1" },
  B2: { ar: "ابدأ من B2", en: "Start with B2" },
};

export const placementCopy = {
  ar: {
    direction: "rtl",
    logoAlt: "شعار Success Academy",
    title: "اعرف أنسب مستوى تبدأ منه",
    description: "تقييم منظم في الاستماع والقراءة واستخدام اللغة، مصمم علشان يحدد نقطة بداية واضحة ومناسبة.",
    fullName: "الاسم بالكامل",
    phone: "رقم الموبايل",
    email: "البريد الإلكتروني (اختياري)",
    consent: "أوافق أن يتواصل معي فريق Success Academy بخصوص نتيجة التقييم والخطوة المناسبة.",
    register: "سجل وابدأ التقييم",
    registering: "جاري إنشاء محاولتك…",
    formError: "راجع البيانات وحاول مرة تانية.",
    serverError: "تعذر حفظ التسجيل دلوقتي. حاول مرة تانية.",
    phoneError: "من فضلك اكتب رقم موبايل صحيح.",
    emailError: "من فضلك اكتب بريد إلكتروني صحيح.",
    requiredError: "الحقل ده مطلوب.",
    resumeTitle: "نكمل من حيث توقفت؟",
    resumeDescription: "محاولتك محفوظة بأمان على نفس الجهاز والمتصفح.",
    continueAttempt: "كمل التقييم",
    startNow: "ابدأ الآن",
    continueLater: "تكمل لاحقًا",
    continueLaterNote: "تقدر ترجع لنفس الصفحة على الجهاز والمتصفح ده وتكمل من مكانك.",
    welcomeTitle: "جاهز تعرف نقطة البداية المناسبة؟",
    welcomeBody: "التقييم فيه 36 سؤال، وغالبًا هياخد من 24 لـ 27 دقيقة. جاوب بأفضل اختيار من غير مساعدة خارجية.",
    audioCheckTitle: "قبل ما نبدأ 🎧",
    audioCheckBody: "اتأكد إن الصوت واضح عندك. استخدم سماعات لو المكان حواليك فيه دوشة.",
    playCheck: "شغّل صوت التجربة",
    soundClear: "الصوت واضح — ابدأ",
    sections: { listening: "الاستماع", reading: "القراءة", languageUse: "استخدام اللغة" } satisfies Record<AssessmentSection, string>,
    sectionIntroTitles: {
      listening: "جاهز تسمع؟ 🎧",
      reading: "وقت القراءة 📖",
      languageUse: "نبدأ بحاجة خفيفة ⚡",
    } satisfies Record<AssessmentSection, string>,
    sectionIntros: {
      listening: "اقرأ السؤال الأول، وبعدها اسمع المحادثة وركز على المعلومة المطلوبة.",
      reading: "مش مطلوب تفهم كل كلمة — ركز على الفكرة والسياق.",
      languageUse: "اختار الإجابة اللي تبدو طبيعية وصحيحة في السياق.",
    } satisfies Record<AssessmentSection, string>,
    beginSection: "ابدأ الجزء",
    assessmentLabel: "اختبار تحديد المستوى",
    questionLabel: "السؤال",
    journey: { start: "البداية", languageUse: "استخدام اللغة", reading: "القراءة", listening: "الاستماع", result: "النتيجة" },
    progressLabel: "تقدم الاختبار",
    timeRemaining: "الوقت المتبقي",
    autoSaveNote: "إجاباتك بتتحفظ تلقائيًا، وتقدر تكمل لاحقًا من نفس الجهاز.",
    readingTime: "وقت مخصص لقراءة النص",
    startQuestions: "ابدأ الأسئلة",
    showPassage: "عرض النص",
    closePassage: "العودة للسؤال",
    playAudio: "شغّل المقطع",
    audioLoading: "جاري تحميل المقطع…",
    audioPlaying: "المقطع شغال…",
    audioUnavailable: "المقطع الصوتي غير متاح حاليًا. حاول مرة تانية لاحقًا.",
    listeningPrompt: "اقرأ السؤال والاختيارات قبل ما تشغّل المقطع.",
    listeningLocked: "الاختيارات هتتفتح أول ما يبدأ الصوت.",
    sharedAudio: "نفس المقطع خاص بالأسئلة المرتبطة دي.",
    audioComplete: "تم الاستماع للمقطع",
    audioOnce: "تشغيل واحد فقط",
    selectAnswer: "اختار إجابة",
    saveAnswer: "حفظ الإجابة والمتابعة",
    saving: "جاري الحفظ…",
    saved: "تم حفظ الإجابة ✓",
    timeout: "انتهى وقت السؤال",
    timeoutTitle: "انتهى وقت السؤال ⏱️",
    timeoutBody: "ولا يهمك — نكمل للسؤال اللي بعده.",
    retry: "حاول مرة تانية",
    networkError: "تعذر حفظ التقدم. اتصالك وإجابتك محفوظين على الشاشة؛ حاول مرة تانية.",
    confirmationTitle: "أسئلة تأكيد قصيرة",
    confirmationBody: "نتيجتك قريبة من حد فاصل، فهنعرض 4 أسئلة إضافية علشان نثبت نقطة البداية بدقة أكبر.",
    analysis: ["بنراجع إجاباتك…", "بنقارن أداءك في المهارات المختلفة…", "بنحدد أنسب نقطة تبدأ منها…"],
    resultHeading: "مستواك المناسب للبدء هو",
    profileTitle: "ملف مستواك",
    strongest: "أقوى جزء",
    improve: "الجزء الأهم للتطوير",
    confidence: "وضوح النتيجة",
    confidenceLabels: { high: "مرتفع", medium: "متوسط", low: "يحتاج تأكيد" },
    whyResult: "ليه النتيجة دي؟",
    whyBody: "النتيجة بتعتمد على أدائك في الاستماع والقراءة واستخدام اللغة عبر درجات صعوبة مختلفة، مش على نسبة صحيحة واحدة بس.",
    courseHeading: "الخطوة المقترحة ليك",
    courseBody: "ابدأ من المستوى المقترح علشان تبني على المهارات اللي ظهرت في التقييم من غير فجوات غير ضرورية.",
    salesCta: "احجز تقييمك مع الفريق",
    fatal: "تعذر فتح المحاولة. ارجع لصفحة التسجيل وابدأ من المسار الآمن.",
    backToRegister: "العودة للتسجيل",
    expired: "انتهت صلاحية المحاولة. سجل من جديد لبدء محاولة آمنة.",
  },
  en: {
    direction: "ltr",
    logoAlt: "Success Academy logo",
    title: "Find the Right Level to Start From",
    description: "A structured Listening, Reading, and Language Use assessment designed to identify a clear and suitable starting point.",
    fullName: "Full Name",
    phone: "Mobile Number",
    email: "Email (optional)",
    consent: "I agree that the Success Academy team may contact me about my result and the appropriate next step.",
    register: "Register and Start",
    registering: "Creating your secure attempt…",
    formError: "Review your details and try again.",
    serverError: "We could not save your registration right now. Please try again.",
    phoneError: "Please enter a valid mobile number.",
    emailError: "Please enter a valid email address.",
    requiredError: "This field is required.",
    resumeTitle: "Continue Where You Stopped?",
    resumeDescription: "Your attempt is securely saved on this device and browser.",
    continueAttempt: "Continue Assessment",
    startNow: "Start Now",
    continueLater: "Continue Later",
    continueLaterNote: "Return to this page on the same device and browser to continue from the same place.",
    welcomeTitle: "Ready to Find Your Best Starting Point?",
    welcomeBody: "The assessment has 36 questions and normally takes 24–27 minutes. Choose your best answer without outside help.",
    audioCheckTitle: "Before We Start 🎧",
    audioCheckBody: "Make sure the sound is clear. Use headphones if your surroundings are noisy.",
    playCheck: "Play Test Sound",
    soundClear: "Sound Is Clear — Start",
    sections: { listening: "Listening", reading: "Reading", languageUse: "English Use" } satisfies Record<AssessmentSection, string>,
    sectionIntroTitles: {
      listening: "Ready to Listen? 🎧",
      reading: "Reading Time 📖",
      languageUse: "Let's Start Light ⚡",
    } satisfies Record<AssessmentSection, string>,
    sectionIntros: {
      listening: "Read the first question, then listen to the conversation and focus on the information you need.",
      reading: "You do not need to understand every word — focus on the idea and context.",
      languageUse: "Choose the answer that sounds natural and correct in context.",
    } satisfies Record<AssessmentSection, string>,
    beginSection: "Start Section",
    assessmentLabel: "Placement Assessment",
    questionLabel: "Question",
    journey: { start: "Start", languageUse: "English Use", reading: "Reading", listening: "Listening", result: "Result" },
    progressLabel: "Assessment progress",
    timeRemaining: "Time remaining",
    autoSaveNote: "Your answers save automatically, so you can continue later on this device.",
    readingTime: "Dedicated Reading Time",
    startQuestions: "Start Questions",
    showPassage: "View Passage",
    closePassage: "Back to Question",
    playAudio: "Play Clip",
    audioLoading: "Loading Audio…",
    audioPlaying: "Audio Playing…",
    audioUnavailable: "This audio clip is not available right now. Please try again later.",
    listeningPrompt: "Read the question and choices before playing the clip.",
    listeningLocked: "Choices unlock as soon as the audio starts.",
    sharedAudio: "The same clip applies to these linked questions.",
    audioComplete: "Clip completed",
    audioOnce: "One play only",
    selectAnswer: "Select an answer",
    saveAnswer: "Save Answer and Continue",
    saving: "Saving…",
    saved: "Answer saved ✓",
    timeout: "Time is up",
    timeoutTitle: "Time's Up ⏱️",
    timeoutBody: "No worries — let's move to the next question.",
    retry: "Try Again",
    networkError: "We could not save your progress. Your on-screen answer is preserved; please retry.",
    confirmationTitle: "A Short Confirmation Check",
    confirmationBody: "Your result is close to a boundary, so four extra questions will confirm the most suitable starting point.",
    analysis: ["Reviewing your answers…", "Comparing performance across skills…", "Finding your best starting point…"],
    resultHeading: "Your Recommended Starting Level Is",
    profileTitle: "Your English Profile",
    strongest: "Strongest Area",
    improve: "Main Area to Improve",
    confidence: "Result Confidence",
    confidenceLabels: { high: "High", medium: "Medium", low: "Confirmation needed" },
    whyResult: "Why This Result?",
    whyBody: "Placement uses your performance across Listening, Reading, and Language Use at different difficulty bands, not one overall raw percentage.",
    courseHeading: "Your Recommended Next Step",
    courseBody: "Start at the recommended level to build on the skills shown in your assessment without unnecessary gaps.",
    salesCta: "Book Your Assessment with the Team",
    fatal: "We could not open this attempt. Return to registration and use the secure start flow.",
    backToRegister: "Back to Registration",
    expired: "This attempt has expired. Register again to start a secure attempt.",
  },
} as const;

export function courseLabel(locale: PlacementLocale, level: PlacementLevel) {
  return sharedCourses[level][locale];
}
