import type { AssessmentSection, PlacementLocale, PlacementLevel } from "./types";

const sharedCourses: Record<PlacementLevel, { ar: string; en: string }> = {
  A1: { ar: "ابدأ من A1", en: "Start with A1" },
  A2: { ar: "ابدأ من A2", en: "Start with A2" },
  B1: { ar: "ابدأ من B1", en: "Start with B1" },
  B2: { ar: "ابدأ من B2", en: "Start with B2" },
};

export const placementCopy = {
  ar: {
    direction: "rtl",
    logoAlt: "شعار Success Academy",
    title: "اعرف أنسب مستوى تبدأ منه",
    description: "تقييم منظم في الاستماع والقراءة واستخدام اللغة، مصمم علشان يحدد نقطة بداية واضحة ومناسبة.",
    fullName: "الاسم بالكامل",
    phone: "رقم الموبايل",
    email: "البريد الإلكتروني (اختياري)",
    consent: "أوافق أن يتواصل معي فريق Success Academy بخصوص نتيجة التقييم والخطوة المناسبة.",
    register: "سجل وابدأ التقييم",
    registering: "جاري إنشاء محاولتك…",
    formError: "راجع البيانات وحاول مرة تانية.",
    serverError: "تعذر حفظ التسجيل دلوقتي. حاول مرة تانية.",
    phoneError: "من فضلك اكتب رقم موبايل صحيح.",
    emailError: "من فضلك اكتب بريد إلكتروني صحيح.",
    requiredError: "الحقل ده مطلوب.",
    resumeTitle: "نكمل من حيث توقفت؟",
    resumeDescription: "محاولتك محفوظة بأمان على نفس الجهاز والمتصفح.",
    continueAttempt: "كمل التقييم",
    startNow: "ابدأ الآن",
    continueLater: "تكمل لاحقًا",
    continueLaterNote: "تقدر ترجع لنفس الصفحة على الجهاز والمتصفح ده وتكمل من مكانك.",
    welcomeTitle: "جاهز تعرف نقطة البداية المناسبة؟",
    welcomeBody: "تقييم سريع في استخدام اللغة، القراءة، والاستماع علشان نحدد أنسب مستوى تبدأ منه.",
    audioCheckTitle: "قبل ما نبدأ 🎧",
    audioCheckBody: "اتأكد إن الصوت واضح عندك. استخدم سماعات لو المكان حواليك فيه دوشة.",
    playCheck: "شغّل صوت التجربة",
    soundClear: "الصوت واضح — ابدأ",
    sections: { listening: "الاستماع", reading: "القراءة", languageUse: "استخدام اللغة" } satisfies Record<AssessmentSection, string>,
    sectionIntroTitles: {
      listening: "آخر تحدي 🎧",
      reading: "وقت القراءة 📖",
      languageUse: "نبدأ بحاجة خفيفة ⚡",
    } satisfies Record<AssessmentSection, string>,
    sectionIntros: {
      listening: "اقرأ السؤال الأول، وبعدها اسمع المحادثة وركز على المعلومة المطلوبة.",
      reading: "مش مطلوب تفهم كل كلمة — ركز على الفكرة والسياق.",
      languageUse: "اختار الإجابة اللي تبدو طبيعية وصحيحة في السياق.",
    } satisfies Record<AssessmentSection, string>,
    assessmentLabel: "اختبار تحديد المستوى",
    questionLabel: "السؤال",
    journey: { languageUse: "استخدام اللغة", reading: "القراءة", listening: "الاستماع", result: "النتيجة" },
    progressLabel: "تقدم الاختبار",
    energyLabel: "طاقة التقدم",
    rewardMessages: [
      { text: "تمام 👌", duration: "short" },
      { text: "كمل 🔥", duration: "short" },
      { text: "ممتاز ✨", duration: "short" },
      { text: "تركيز حلو ⚡", duration: "normal" },
      { text: "خطوة كمان ✅", duration: "short" },
      { text: "مركز جدًا 👀", duration: "normal" },
      { text: "يلا نكمل 🚀", duration: "normal" },
    ],
    bonusMessages: ["4 خطوات ورا بعض!", "Bonus streak ⚡", "Momentum +1 🔥"],
    sectionComplete: {
      languageUse: "استخدام اللغة خلص ✅",
      reading: "القراءة خلصت ✅",
      listening: "الاستماع خلص ✅",
    } satisfies Record<AssessmentSection, string>,
    timeRemaining: "الوقت المتبقي",
    autoSaveNote: "إجاباتك بتتحفظ تلقائيًا، وتقدر تكمل لاحقًا من نفس الجهاز.",
    readingPreparation: "وقت قراءة مقترح",
    readingPreparationHint: "السؤال قدامك — اختار إجابتك وقت ما تكون جاهز.",
    showPassage: "عرض النص",
    closePassage: "العودة للسؤال",
    playAudio: "شغّل المقطع",
    audioLoading: "جاري تحميل المقطع…",
    audioPlaying: "المقطع شغال…",
    audioUnavailable: "المقطع الصوتي غير متاح حاليًا. حاول مرة تانية لاحقًا.",
    listeningPrompt: "اقرأ السؤال والاختيارات قبل ما تشغّل المقطع.",
    listeningLocked: "الاختيارات هتتفتح أول ما يبدأ الصوت.",
    sharedAudio: "نفس المقطع خاص بالأسئلة المرتبطة دي.",
    listeningBlockCount: "التسجيل ده عليه {count} أسئلة",
    listeningBlockPreview: "اقرأ الأسئلة الأول، وبعدها شغّل التسجيل وركز على المعلومات المطلوبة.",
    listeningBlockReview: "التسجيل خلص — راجع اختيارك وكمل الأسئلة المرتبطة.",
    audioComplete: "تم الاستماع للمقطع",
    audioOnce: "تشغيل واحد فقط",
    selectAnswer: "اختار إجابة",
    saveAnswer: "التالي",
    saving: "لحظة…",
    timeoutTitle: "انتهى وقت السؤال ⏱️",
    timeoutBody: "نكمل للسؤال اللي بعده.",
    retry: "حاول مرة تانية",
    networkError: "تعذر حفظ التقدم. اتصالك وإجابتك محفوظين على الشاشة؛ حاول مرة تانية.",
    confirmationTitle: "أسئلة تأكيد قصيرة",
    confirmationBody: "نتيجتك قريبة من حد فاصل، فهنعرض 4 أسئلة إضافية علشان نثبت نقطة البداية بدقة أكبر.",
    analysis: ["بنراجع إجاباتك…", "بنقارن أداءك في المهارات المختلفة…", "بنحدد أنسب نقطة تبدأ منها…"],
    resultComplete: "عاش! خلصت التقييم 🎉",
    resultHeading: "مستواك المناسب للبدء هو",
    resultBasis: "بناءً على إجاباتك في استخدام اللغة، القراءة، والاستماع.",
    profileTitle: "تحليل أدائك",
    strongest: "أقوى مهارة",
    improve: "أهم نقطة للتحسين",
    confidence: "درجة الثقة في النتيجة",
    confidenceLabels: { high: "مرتفع", medium: "متوسط", low: "يحتاج تأكيد" },
    qualitativeLabels: { A1: "يحتاج تأسيس", A2: "يحتاج تطوير", B1: "جيد", B2: "أقوى" } satisfies Record<PlacementLevel, string>,
    whyResult: "ليه النتيجة دي؟",
    whyBody: "النتيجة بتعتمد على الصورة الكاملة في الاستماع والقراءة واستخدام اللغة عبر درجات صعوبة مختلفة، مش على نسبة صحيحة واحدة بس. ممكن تكون أقوى في مهارة معينة من غير ما يكون باقي الأداء بنفس المستوى.",
    courseHeading: "الخطوة الجاية",
    courseBody: "ابدأ من المستوى المقترح علشان تبني على المهارات اللي ظهرت في التقييم من غير فجوات غير ضرورية.",
    salesCta: "احجز مع فريق Success Academy",
    homepageCta: "ابدأ خطوتك الجاية",
    whatsappCta: "كلّمنا على واتساب",
    fatal: "تعذر فتح المحاولة. ارجع لصفحة التسجيل وابدأ من المسار الآمن.",
    backToRegister: "العودة للتسجيل",
    expired: "انتهت صلاحية المحاولة. سجل من جديد لبدء محاولة آمنة.",
  },
  en: {
    direction: "ltr",
    logoAlt: "Success Academy logo",
    title: "Find the Right Level to Start From",
    description: "A structured Listening, Reading, and Language Use assessment designed to identify a clear and suitable starting point.",
    fullName: "Full Name",
    phone: "Mobile Number",
    email: "Email (optional)",
    consent: "I agree that the Success Academy team may contact me about my result and the appropriate next step.",
    register: "Register and Start",
    registering: "Creating your secure attempt…",
    formError: "Review your details and try again.",
    serverError: "We could not save your registration right now. Please try again.",
    phoneError: "Please enter a valid mobile number.",
    emailError: "Please enter a valid email address.",
    requiredError: "This field is required.",
    resumeTitle: "Continue Where You Stopped?",
    resumeDescription: "Your attempt is securely saved on this device and browser.",
    continueAttempt: "Continue Assessment",
    startNow: "Start Now",
    continueLater: "Continue Later",
    continueLaterNote: "Return to this page on the same device and browser to continue from the same place.",
    welcomeTitle: "Ready to Find Your Best Starting Point?",
    welcomeBody: "A focused challenge across English Use, Reading, and Listening to find the most suitable level for you to start from.",
    audioCheckTitle: "Before We Start 🎧",
    audioCheckBody: "Make sure the sound is clear. Use headphones if your surroundings are noisy.",
    playCheck: "Play Test Sound",
    soundClear: "Sound Is Clear — Start",
    sections: { listening: "Listening", reading: "Reading", languageUse: "English Use" } satisfies Record<AssessmentSection, string>,
    sectionIntroTitles: {
      listening: "Final Challenge 🎧",
      reading: "Reading Time 📖",
      languageUse: "Let's Start Light ⚡",
    } satisfies Record<AssessmentSection, string>,
    sectionIntros: {
      listening: "Read the first question, then listen to the conversation and focus on the information you need.",
      reading: "You do not need to understand every word — focus on the idea and context.",
      languageUse: "Choose the answer that sounds natural and correct in context.",
    } satisfies Record<AssessmentSection, string>,
    assessmentLabel: "Placement Assessment",
    questionLabel: "Question",
    journey: { languageUse: "English Use", reading: "Reading", listening: "Listening", result: "Result" },
    progressLabel: "Assessment progress",
    energyLabel: "Journey Energy",
    rewardMessages: [
      { text: "Nice! 👏", duration: "short" },
      { text: "Keep going 🚀", duration: "short" },
      { text: "Great focus ⚡", duration: "normal" },
      { text: "Strong step ✨", duration: "normal" },
      { text: "One more ✅", duration: "short" },
      { text: "Locked in 👀", duration: "normal" },
      { text: "Good momentum 🔥", duration: "normal" },
    ],
    bonusMessages: ["4 steps in a row!", "Bonus streak ⚡", "Momentum +1 🔥"],
    sectionComplete: {
      languageUse: "English Use complete ✅",
      reading: "Reading complete ✅",
      listening: "Listening complete ✅",
    } satisfies Record<AssessmentSection, string>,
    timeRemaining: "Time remaining",
    autoSaveNote: "Your answers save automatically, so you can continue later on this device.",
    readingPreparation: "Suggested reading time",
    readingPreparationHint: "The question is ready — choose when you feel prepared.",
    showPassage: "View Passage",
    closePassage: "Back to Question",
    playAudio: "Play Clip",
    audioLoading: "Loading Audio…",
    audioPlaying: "Audio Playing…",
    audioUnavailable: "This audio clip is not available right now. Please try again later.",
    listeningPrompt: "Read the question and choices before playing the clip.",
    listeningLocked: "Choices unlock as soon as the audio starts.",
    sharedAudio: "The same clip applies to these linked questions.",
    listeningBlockCount: "This recording has {count} questions",
    listeningBlockPreview: "Read all the questions first, then play the recording and focus on the information you need.",
    listeningBlockReview: "The recording is complete — review your choice and continue through the linked questions.",
    audioComplete: "Clip completed",
    audioOnce: "One play only",
    selectAnswer: "Select an answer",
    saveAnswer: "Continue",
    saving: "One moment…",
    timeoutTitle: "Time's Up ⏱️",
    timeoutBody: "Let's move to the next question.",
    retry: "Try Again",
    networkError: "We could not save your progress. Your on-screen answer is preserved; please retry.",
    confirmationTitle: "A Short Confirmation Check",
    confirmationBody: "Your result is close to a boundary, so four extra questions will confirm the most suitable starting point.",
    analysis: ["Reviewing your answers…", "Comparing performance across skills…", "Finding your best starting point…"],
    resultComplete: "Nice work! Assessment complete 🎉",
    resultHeading: "Your Recommended Starting Level Is",
    resultBasis: "Based on your answers across English Use, Reading, and Listening.",
    profileTitle: "Your Performance Profile",
    strongest: "Strongest Area",
    improve: "Main Area to Improve",
    confidence: "Result Confidence",
    confidenceLabels: { high: "High", medium: "Medium", low: "Confirmation needed" },
    qualitativeLabels: { A1: "Needs foundations", A2: "Needs development", B1: "Good", B2: "Strongest" } satisfies Record<PlacementLevel, string>,
    whyResult: "Why This Result?",
    whyBody: "Placement uses your full profile across Listening, Reading, and Language Use at different difficulty bands, not one overall raw percentage. One skill can be stronger without the rest of the profile being at the same level.",
    courseHeading: "Your Next Step",
    courseBody: "Start at the recommended level to build on the skills shown in your assessment without unnecessary gaps.",
    salesCta: "Talk to the Success Academy Team",
    homepageCta: "Start Your Next Step",
    whatsappCta: "Chat with us on WhatsApp",
    fatal: "We could not open this attempt. Return to registration and use the secure start flow.",
    backToRegister: "Back to Registration",
    expired: "This attempt has expired. Register again to start a secure attempt.",
  },
} as const;

export function courseLabel(locale: PlacementLocale, level: PlacementLevel) {
  return sharedCourses[level][locale];
}
